### ISSUE TITLE
Add unsubscription mechanism

### ISSUE THREAD

**Issue by GianlucaGuarini** [GianlucaGuarini/erre#2]
The users should be able to unsubscribe registered callbacks. See also https://github.com/riot/riot/issues/2708#issuecomment-501443045

**Comment by GianlucaGuarini** [comment]
@jayshoo I have seen you are working also on a patch to add this feature. Could you please PR so I will make a new release? thank you

**Comment by jayshoo** [comment]
please know that i made this patch just for my own project. there may be big design problems, i have not thought much about it.

created pr #3.
currently test.js fails eslint.
